import '@/styles/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Week 4 Devscale',
  description: 'Generated by followng devscale bootcamp',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-xl m-auto my-12">
          {children}
        </main>
      </body>
    </html>
  )
}
